server:
  port: 8083

spring:
  application:
    name: cloud-consumer1

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8848/eureka/
hystrix:
  command:
    default: #也可以针对多个服务
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 设置hystrix的超时时间为4000ms
feign:
  hystrix:
    enabled: true
    # hystrix 的超时时间

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
  MaxTotalHttpConnections: 500
  MaxConnectionsPerHost: 100
